# Build stage
FROM node:22-alpine as builder

WORKDIR /app

COPY package*.json ./
COPY index.html ./
COPY vite.config.ts ./
COPY tsconfig*.json ./
COPY src/ ./src/
COPY public/ ./public/
COPY .env.production ./

RUN npm ci && npm run build

# Runtime stage (serve)
FROM node:22-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]