# Backend API Dockerfile
FROM node:22-alpine

WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./
COPY prisma ./prisma/

# Installer les dépendances
RUN npm install

# Copier le reste de l'application
COPY . .

# Générer le client Prisma
RUN npx prisma generate

# Exposer le port API
EXPOSE 3000

# CMD exécutera la commande définie dans docker-compose.yml
CMD ["npm", "run", "dev:api"]
