FROM node:22-alpine

WORKDIR /app

# installe d'abord les dependances
COPY package*.json ./
RUN npm ci

# app source
COPY . .

# avoid watching heavy folders
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 5173

CMD ["npm", "run", "dev"]