FROM node:22-alpine AS build

WORKDIR /app

# dependances
COPY package*.json ./
RUN npm ci

# source
COPY . .

# build de l'application
RUN npm run build


# -------------------------
# serveur nginx
# -------------------------
FROM nginx:alpine

# copie le build vite
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]