FROM node:22-alpine

WORKDIR /app

# 1. package.json d'abord (cache Docker)
COPY package*.json ./

# 2. install unique propre
RUN npm ci --legacy-peer-deps

# 3. Prisma schema seulement
COPY prisma ./prisma/

# 4. generate Prisma client
RUN npx prisma generate

# 5. reste du code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev:api"]